# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: [vendor]

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Code for Croatia Zero
description: URL shortener za Code for Croatia team.
baseurl: "zero" # the subpath of your site, e.g. /blog
url: "https://codeforcroatia.github.io" # the base hostname & protocol for your site
github_repo: zero # the GitHub repo name for your project
github_username: codeforcroatia
portal:
  name: Code for Croatia
  url: "https://codeforcroatia.org"
  app: Laddr
  type: Civic hacking activists
  domain: codeforcroatia.org

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: codeforcroatia

# custom social link Facebook
social_fb_username: programirajzahrvatsku

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow; violet (custom); redinverted (custom).
theme_color: redinverted

# Build settings
markdown: kramdown

# Site analytics
analytics:
  provider: google
  google:
    id: UA-46708458-15
