#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site --disable-external --url-ignore "/zero/,/zero/articles/,/zero/slides/,/zero/documents/,/zero/sheets/,/zero/projects/,/zero/i/" ./out
